export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DECREASE_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREASE_FROM_CART = "REMOVE_FROM_CART";

export const GET_SUMMARY = "GET_SUMMARY";

// authentication
export const REGISTER_SUCCESSFULL = "REGISTER_SUCCESSFULL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const USER_LOADED_SUCCESSFUL = "USER_LOADED_SUCCESSFUL";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";

// reset passwrod
export const PASSWORD_RESET_SUCCESSFULL = "PASSWORD_RESET_SUCCESSFULL";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESSFUL =
  "PASSWORD_RESET_CONFIRM_SUCCESSFUL";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";

// adress sent
export const ADRESS_SUCCESS = "ADRESS_SUCCESS";
export const ADRESS_FAIL = "ADRESS_FAIL";

// order actions
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
